server:
  port: 8006

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test_db?characterEncoding=utf8&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      username: root
      password: root
      stat-view-servlet:
        login-username: codedreamplus
        login-password: codedreamplus
        reset-enable: false
        url-pattern: /druid/*
        enabled: true
      initial-size: 10
      max-active: 50
      max-wait: 5000
      filters: stat,wall,slf4j


codedreamplus:
  mybatis-plus:
    tenant-mode: false
    block-attack: true